-- PRODUCT INSERT 
INSERT INTO PRODUCT
VALUES (PRODUCT_SEQ.NEXTVAL, 'A개껌', '좋아요', 4.1);

SELECT * FROM PRODUCT;

-- PRODUCT_OPTION INSERT
INSERT INTO PRODUCT_OPTION
VALUES (OPTION_SEQ.NEXTVAL, 2, '사료 추가', 5000, 4);

SELECT * FROM PRODUCT_OPTION;

COMMIT;
ROLLBACK;
