-----------------------------------------------------------
---- 회원 관리
-- 1. MEMBER (회원)

CREATE TABLE MEMBER (
	ID VARCHAR2(100) CONSTRAINTS M_ID_PK PRIMARY KEY,
	PW VARCHAR2(100),
	NAME VARCHAR2(100),
	PHONE VARCHAR2(100),
	EMAIL VARCHAR2(100),
	ADDRESS VARCHAR2(100)
)

INSERT INTO MEMBER
VALUES ('mhj', '1234', '명혜진', '010-1234-5678', 'mhj@gmail.com', '서울특별시 금천구 ~');

SELECT * FROM MEMBER;
DROP TABLE MEMBER;

-----------------------------------------------------------
-- 2. MEMBER_ROLE (멤버 권한)

CREATE TABLE MEMBER_ROLE (
	ID VARCHAR2(100),
	ROLENUM NUMBER
)

ALTER TABLE MEMBER_ROLE ADD CONSTRAINTS MR_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID);
ALTER TABLE MEMBER_ROLE ADD CONSTRAINTS MR_RN_FK FOREIGN KEY (ROLENUM) REFERENCES ROLE (ROLENUM);

SELECT * FROM MEMBER_ROLE;
DROP TABLE MEMBER_ROLE;

-----------------------------------------------------------
-- 3. ROLE (권한)

CREATE TABLE ROLE (
	ROLENUM NUMBER CONSTRAINTS R_N_PK PRIMARY KEY,
	ROLENAME VARCHAR2(100)
)

SELECT * FROM ROLE;
DROP TABLE ROLE;

INSERT INTO ROLE
VALUES (1, '관리자');

INSERT INTO ROLE
VALUES (2, '일반 회원');

-----------------------------------------------------------

-----------------------------------------------------------
---- 은행 관리
-- 1. ACCOUNT (계좌)

CREATE TABLE ACCOUNT (
	BANKBOOKNUM NUMBER,
	ID VARCHAR2(100),
	ACCOUNTNUM NUMBER CONSTRAINTS AC_AN_PK PRIMARY KEY,
	ACCOUNTDATE DATE,
	ACCOUNTMONEY NUMBER
)

ALTER TABLE ACCOUNT ADD CONSTRAINTS AC_BN_FK FOREIGN KEY (BANKBOOKNUM) REFERENCES BANKBOOK (BANKBOOKNUM); 
ALTER TABLE ACCOUNT ADD CONSTRAINTS AC_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID);

SELECT * FROM ACCOUNT;

INSERT INTO ACCOUNT
VALUES (2, 'mhj', '1111', SYSDATE, 0);

-----------------------------------------------------------
-- 2. BANKBOOK (통장)

CREATE TABLE BANKBOOK (
	BANKBOOKNUM NUMBER CONSTRAINTS BB_BN_PK PRIMARY KEY,
	BANKBOOKNAME VARCHAR2(100),
	BANKBOOKRATE NUMBER(3,1),
	BANKBOOKDETAIL CLOB,
	BANKBOOKSELL VARCHAR2(100) 
)

ALTER TABLE BANKBOOK ADD CONSTRAINTS BB_BS_C CHECK (BANKBOOKSELL IN ('Y', 'N'));

SELECT * FROM BANKBOOK;

CREATE SEQUENCE BANKBOOK_SEQ
START WITH 1;

INSERT INTO BANKBOOK
VALUES (BANKBOOK_SEQ.NEXTVAL, 'OO통장', 3.7, '이자율이 높은 통장', 'Y');

-----------------------------------------------------------
-- 3. INOUTSERACH (입출금내역)

CREATE TABLE INOUTSEARCH (
	INOUTNUM NUMBER CONSTRAINTS IS_IN_PK PRIMARY KEY,
	ACCOUNTNUM NUMBER,
	INOUTMONEY NUMBER,
	INPUTDATE DATE
)

ALTER TABLE INOUTSEARCH ADD CONSTRAINTS IS_AN_FK FOREIGN KEY (ACCOUNTNUM) REFERENCES ACCOUNT (ACCOUNTNUM);

SELECT * FROM INOUTSEARCH;

INSERT INTO INOUTSEARCH
VALUES (INPUT_SEQ.NEXTVAL, 1111, 5000, SYSDATE);

CREATE SEQUENCE INPUT_SEQ
START WITH 1;

COMMIT;
ROLLBACK;



SELECT * FROM USER_CONSTRAINTS;
PURGE RECYCLEBIN;
